/*CREATE DATABASE IF EXISTS truequeando_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;*/

CREATE TABLE IF NOT EXISTS rols (
    id SMALLSERIAL PRIMARY KEY NOT NULL CHECK (id >= 0),
    name VARCHAR NOT NULL CHECK (name <> ''),
    state BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL,
	user_id INT NOT NULL CHECK (user_id >= 0),
    user_name VARCHAR NOT NULL CHECK (user_name <> ''),
	--change_password BOOLEAN DEFAULT FALSE NOT NULL,
    user_state BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS passwords (
    id SMALLSERIAL PRIMARY KEY NOT NULL,
	users_id INT NOT NULL REFERENCES users(id) CHECK (users_id >= 0),
    password JSONB NOT NULL,
    state BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS rols_users (
    id SERIAL PRIMARY KEY NOT NULL,
	rols_id INT NOT NULL REFERENCES rols(id) CHECK (rols_id >= 0),
	user_id INT NOT NULL REFERENCES users(id) CHECK (user_id >= 0),
    state BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS types_document_identification (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL,
	state BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS type_gener (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL,
	state BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS country (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL,
	state BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS states (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL,
	country_id INT REFERENCES country(id) NOT NULL,
	state BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS city (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL,
	states_id INT REFERENCES states(id) NOT NULL,
	state BOOLEAN NOT NULL DEFAULT TRUE
);
